# Generated by Django 3.1.7 on 2021-03-24 13:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recruiting_service', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='test',
            old_name='orden_code',
            new_name='order_code',
        ),
    ]
