# Generated by Django 3.1.7 on 2021-03-28 18:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recruiting_service', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShadowHand',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recruit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='recruiting_service.recruit', verbose_name='Рекрут')),
                ('sith', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='recruiting_service.sith', verbose_name='Ситх')),
            ],
            options={
                'verbose_name': 'Рука Тени',
                'verbose_name_plural': 'Руки Тени',
            },
        ),
    ]
