# Generated by Django 3.1.7 on 2021-03-24 15:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recruiting_service', '0002_auto_20210324_1649'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='test',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='recruiting_service.test'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='variant',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='recruiting_service.question', verbose_name='Вопрос'),
        ),
    ]
