# Generated by Django 3.1.7 on 2021-03-24 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruiting_service', '0003_auto_20210324_1853'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='visible',
            field=models.BooleanField(default=True, verbose_name='Видимость'),
        ),
    ]
