# Generated by Django 3.1.7 on 2021-03-24 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruiting_service', '0004_test_visible'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recruit',
            name='email',
            field=models.EmailField(max_length=200, verbose_name='Email'),
        ),
    ]
