# Generated by Django 3.1.7 on 2021-03-28 15:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('recruiting_service', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=2048, verbose_name='Вопрос')),
            ],
            options={
                'verbose_name': 'Вопрос',
                'verbose_name_plural': 'Вопросы',
            },
        ),
        migrations.CreateModel(
            name='Variant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=1024, verbose_name='Вариант ответа')),
            ],
            options={
                'verbose_name': 'Вариант ответа',
                'verbose_name_plural': 'Варианты ответа',
            },
        ),
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Наименование теста')),
                ('order_code', models.CharField(max_length=255, unique=True, verbose_name='Уникальный код ордена')),
                ('is_visible', models.BooleanField(default=True, verbose_name='Отображение')),
                ('questions', models.ManyToManyField(to='test_service.Question', verbose_name='Вопросы')),
            ],
            options={
                'verbose_name': 'Тестовое испытание',
                'verbose_name_plural': 'Тестовые испытания',
            },
        ),
        migrations.CreateModel(
            name='Result',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mark_as_pass', models.BooleanField(default=False, verbose_name='Отметка о прохождение')),
                ('datetime_of_completion', models.DateTimeField(auto_now_add=True, verbose_name='Дата и время выполнения')),
                ('recruit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='recruiting_service.recruit', verbose_name='Рекрут')),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='test_service.test', verbose_name='Тест')),
            ],
            options={
                'verbose_name': 'Результат',
                'verbose_name_plural': 'Результаты',
            },
        ),
        migrations.AddField(
            model_name='question',
            name='variants',
            field=models.ManyToManyField(to='test_service.Variant', verbose_name='Варианты ответов'),
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='test_service.question', verbose_name='Вопрос')),
                ('recruit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='recruiting_service.recruit', verbose_name='Рекрут')),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='test_service.test', verbose_name='Тест')),
                ('variant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='test_service.variant', verbose_name='Вариант')),
            ],
            options={
                'verbose_name': 'Ответ на тест',
                'verbose_name_plural': 'Ответы на тест',
            },
        ),
    ]
